In [7]:
import pandas as pd
obj = pd.Series([4,7,-5,3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [8]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [10]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [16]:
obj2=pd.Series([4,7,-5,3], index=['a','b','c','d'])
obj2

a    4
b    7
c   -5
d    3
dtype: int64

In [17]:
obj2.index # dtype 도 잘 보라 !

Index(['a', 'b', 'c', 'd'], dtype='object')

In [18]:
obj2.values

array([ 4,  7, -5,  3], dtype=int64)

In [20]:
obj2['a']

4

In [21]:
obj2['b']=5
obj2

a    4
b    5
c   -5
d    3
dtype: int64

In [25]:
obj2[['c','a','d']] # index 순서대로 values 출력됨.

c   -5
a    4
d    3
dtype: int64

In [27]:
obj2

a    4
b    5
c   -5
d    3
dtype: int64

In [31]:
print(obj2[obj2<0].values)

[-5]


In [32]:
obj2[obj2<0].values

array([-5], dtype=int64)

In [37]:
obj2[obj2<0]

c   -5
dtype: int64

In [38]:
import numpy as np
np.exp(obj2)

a     54.598150
b    148.413159
c      0.006738
d     20.085537
dtype: float64

In [40]:
'b' in obj2

True

In [41]:
'e' in obj2

False

In [44]:
sdata = {'Ohio': 35000, 'Texas':71000, 'Oregon':16000, 'Utah':5000}
#Python Dictionary 
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [49]:
states = ['California','Ohio','Oregon','Texas'] #색인을 직접 지정
obj4 = pd.Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [50]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [51]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [52]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [53]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [54]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [55]:
obj3+obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [58]:
obj4.name = 'popluation' # series 이름은 population
obj4.index.name = 'state'# index 이름은 state

obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: popluation, dtype: float64

In [59]:
obj = pd.Series([4,7,-5,3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [61]:
obj.index = ['Bob','Steve','Jeff','Ryan']
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [62]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
       'year' : [2000, 2001, 2002, 2001, 2002, 2003],
       'pop' : [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

frame = pd.DataFrame(data)
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [63]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [64]:
frame.tail()

state  year  pop
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [66]:
pd.DataFrame(data, columns=['year','pop','state'])


year  pop   state
0  2000  1.5    Ohio
1  2001  1.7    Ohio
2  2002  3.6    Ohio
3  2001  2.4  Nevada
4  2002  2.9  Nevada
5  2003  3.2  Nevada

In [67]:
pd.DataFrame(data, columns=['year','state'])

year   state
0  2000    Ohio
1  2001    Ohio
2  2002    Ohio
3  2001  Nevada
4  2002  Nevada
5  2003  Nevada

In [68]:
frame2 = pd.DataFrame(data , columns=['year','state','pop','debt'],
                     index = ['one', 'two', 'three', 'four', 'five', 'six'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [69]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [85]:
frame2['debt'] = 16.5
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [90]:
frame2['debt'] = np.arange(6)
frame2

year   state  pop  debt
one    2000    Ohio  1.5     0
two    2001    Ohio  1.7     1
three  2002    Ohio  3.6     2
four   2001  Nevada  2.4     3
five   2002  Nevada  2.9     4
six    2003  Nevada  3.2     5

In [91]:
val = pd.Series([-1.2, -1.5, -1.7], index = ['two','four','five'])
frame2['debt'] = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [102]:
frame2['eastern'] = frame2.state == 'Ohio'
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [103]:
del frame2['eastern'] # 열 삭제
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [104]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [129]:
#중첩된 dictionary를 이용하여 데이터를 생성할 수있다. 
# 중첩된 dictionary를 DataFrame에 넘기면, 바깥의 키는 컬럼이 되고 안쪽의 키는 로우가 된다.
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
      'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

frame3 = pd.DataFrame(pop)
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [130]:
pd.DataFrame(pop, index = [2001,2002,2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [134]:
pdata = {'Ohio': frame3['Ohio'][:-1],
        'Nevada' : frame3['Nevada'][:2]}
pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [136]:
frame3.index.name = 'year'
frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [140]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [142]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [143]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [150]:
obj = pd.Series(range(3), index=['a','b','c'])
obj

a    0
b    1
c    2
dtype: int64

In [156]:
obj.index[1]
obj.index

In [159]:
labels = pd.Index(np.arange(3))
labels

Int64Index([0, 1, 2], dtype='int64')

In [160]:
obj2 = pd.Series([1.5,-2.5, 0], index = labels)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [161]:
obj2.index is labels

True

In [162]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [163]:
frame3.index

Int64Index([2001, 2002, 2000], dtype='int64', name='year')

In [164]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [166]:
'Ohio' in frame3.columns

True

In [170]:
2000 in frame3.index

True

In [171]:
2004 in frame3.index

False

In [173]:
dup_labels = pd.Index(['foo','foo','bar','bar'])
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [178]:
obj=pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [182]:
obj2= obj.reindex(['a','b','c','d','e'])
obj2
# 존재안하는건 NaN 입니다.

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [183]:
obj3 = pd.Series(['blue','purple','yellow'], index=[0,2,4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [188]:
obj3.reindex(range(6), method='ffill') # forward 앞에꺼 따라하기

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [189]:
obj3.reindex(range(6), method='bfill') # back 뒤에꺼 따라하기.

0      blue
1    purple
2    purple
3    yellow
4    yellow
5       NaN
dtype: object

In [192]:
#DataFrame에 대한 reindex는 row, col 둘다 변경 가능하다.
frame = pd.DataFrame(np.arange(9).reshape(3,3),
                     index=['a','c','d'], columns=['Ohio', 'Texas', 'California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [194]:
frame2 = frame.reindex(['a','b','c','d'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [196]:
states = ['Texas','Ultra','California']
frame.reindex(columns=states)

Texas  Ultra  California
a      1    NaN           2
c      4    NaN           5
d      7    NaN           8

In [211]:
import numpy as np
obj = pd.Series(np.arange(5), index=['a','b','c','d','e'])
obj

a    0
b    1
c    2
d    3
e    4
dtype: int32

In [206]:
obj.drop('c')

a    0
b    1
d    3
e    4
dtype: int32

In [207]:
obj

a    0
b    1
c    2
d    3
e    4
dtype: int32

In [212]:
obj.drop(['d','c'])

a    0
b    1
e    4
dtype: int32

In [215]:
data = pd.DataFrame(np.arange(16).reshape(4,4),
  index = ['Ohio','Colorado','Utah','New York'],
                   columns = ['one','two','three','four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [216]:
data.drop(['Colorado','Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [219]:
data.drop(['two','four'],axis='columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [220]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [226]:
obj = pd.Series(np.arange(5), index=['a','b','c','d','e'])
obj.drop('c')

a    0
b    1
d    3
e    4
dtype: int32

In [227]:
obj

a    0
b    1
c    2
d    3
e    4
dtype: int32

In [228]:
obj.drop('c',inplace=True) # 영구 삭제

In [229]:
obj

a    0
b    1
d    3
e    4
dtype: int32

In [255]:
obj = pd.Series(np.arange(4), index =['a','b','c','d'])
obj

a    0
b    1
c    2
d    3
dtype: int32

In [231]:
obj['b']

1

In [232]:
obj[1]

1

In [233]:
obj[2:4]

c    2
d    3
dtype: int32

In [243]:
obj[2:4]

c    2
d    3
dtype: int32

In [245]:
obj[['b','a','d']]

b    1
a    0
d    3
dtype: int32

In [246]:
obj[[1,3]]

b    1
d    3
dtype: int32

In [256]:
obj[obj<2] # 값이 2보다 작은거 출력 .index 아님

a    0
b    1
dtype: int32

In [257]:
obj['b':'c']

b    1
c    2
dtype: int32

In [259]:
obj['b':'c'] = 5
obj

a    0
b    5
c    5
d    3
dtype: int32

In [260]:
obj

a    0
b    5
c    5
d    3
dtype: int32

In [261]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),
                   index = ['Ohio','Colorado','Utah','New York'],
                   columns = ['one','two','three','four'])

data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [264]:
data[['two']]

two
Ohio        1
Colorado    5
Utah        9
New York   13

In [265]:
data[['three','one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [266]:
data[data['three']>5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [267]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [268]:
data[data<5] = 0
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [269]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [271]:
data.loc[['Colorado']]

one  two  three  four
Colorado    0    5      6     7

In [276]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int32

In [278]:
data.iloc[2,[3,0,1]]

four    11
one      8
two      9
Name: Utah, dtype: int32

In [279]:
data.iloc[[1,2],[3,0,1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [280]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [283]:
data.loc[:'Utah',:'two']

one  two
Ohio        0    0
Colorado    0    5
Utah        8    9

In [287]:
data.loc[:'Utah','two'] # Utah 포함입니다. 

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [288]:
data.iloc[:3,1] # 2까지 입니다.

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [289]:
data.iloc[:,:3]

one  two  three
Ohio        0    0      0
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [291]:
data.iloc[:3]

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11

In [292]:
data.iloc[:,:3][data.three>0]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [293]:
ser = pd.Series(np.arange(3))
ser

0    0
1    1
2    2
dtype: int32

In [296]:
ser[-1]

KeyError: -1

In [297]:
ser2 = pd.Series(np.arange(3.), index=['a','b','c'])  #정수 기반의 색인을 사용하지 않으면 이러한 모호함은 사라진다.
ser2[-1]

2.0

In [298]:
ser[:1]

0    0
dtype: int32

In [299]:
ser.loc[:1]

0    0
1    1
dtype: int32

In [300]:
ser.iloc[:1]

0    0
dtype: int32

In [301]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a','c','d','e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index = ['a','c','e','f','g'])

s1


a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [302]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [303]:
s1+s2 # 두개 다 값이 있으면 + 하고 없으면 NaN 입니다.

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [307]:
df1 = pd.DataFrame(np.arange(9).reshape((3,3)), columns=list('bcd'), 
                   index=['Ohio', 'Texas', 'Colorado'])
df2 = pd.DataFrame(np.arange(12).reshape((4,3)), columns=list('bde'), 
                   index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [308]:
df1

b  c  d
Ohio      0  1  2
Texas     3  4  5
Colorado  6  7  8

In [309]:
df2

b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [310]:
df1+df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [313]:
df1 = pd.DataFrame({'A':[1,2]})
df2 = pd.DataFrame({'B':[3,4]})
df1

A
0  1
1  2

In [314]:
df2

B
0  3
1  4

In [315]:
df1-df2

A   B
0 NaN NaN
1 NaN NaN

In [336]:
df1 = pd.DataFrame(np.arange(12).reshape((3,4)), columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20).reshape((4,5)), columns=list('abcde'))
df1

a  b   c   d
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [319]:
df2

a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19

In [322]:
df2.loc[1, 'b'] = np.nan
df2

a     b   c   d   e
0   0   1.0   2   3   4
1   5   NaN   7   8   9
2  10  11.0  12  13  14
3  15  16.0  17  18  19

In [323]:
df1

a  b   c   d
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [324]:
df2

a     b   c   d   e
0   0   1.0   2   3   4
1   5   NaN   7   8   9
2  10  11.0  12  13  14
3  15  16.0  17  18  19

In [325]:
df1+df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [329]:
df1.add(df2, fill_value=0) # df1+df2인데 NaN값을 0으로 바꿔서 더한다는 의미.

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [330]:
1/df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [331]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [332]:
df1.div(1)

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [338]:
df1.reindex(columns = df2.columns, fill_value=0)

a  b   c   d  e
0  0  1   2   3  0
1  4  5   6   7  0
2  8  9  10  11  0

In [339]:
df1.radd(df2)

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [341]:
arr= np.arange(12).reshape((3,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [343]:
arr - arr[0]

array([[0, 0, 0, 0],
       [4, 4, 4, 4],
       [8, 8, 8, 8]])

In [348]:
frame = pd.DataFrame(np.arange(12).reshape((4,3)),
                    columns = list('bde'),
                    index = ['Utah', 'Ohio', 'Texas', 'Oregon'])
series = frame.iloc[0]

In [349]:
frame

b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [350]:
series

b    0
d    1
e    2
Name: Utah, dtype: int32

In [353]:
series3 = frame['d']
series3

Utah       1
Ohio       4
Texas      7
Oregon    10
Name: d, dtype: int32

In [355]:
frame.sub(series3, axis='index')
# 빼기 연산

b  d  e
Utah   -1  0  1
Ohio   -1  0  1
Texas  -1  0  1
Oregon -1  0  1

In [357]:
frame = pd.DataFrame(np.random.randn(4,3), columns= list('bde'),
                    index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b         d         e
Utah   -1.519942 -0.576650 -0.809263
Ohio    0.328608 -0.935240 -0.547198
Texas   0.389365 -1.497145 -1.088646
Oregon  0.385908 -1.832977 -0.115558

In [358]:
np.abs(frame)

b         d         e
Utah    1.519942  0.576650  0.809263
Ohio    0.328608  0.935240  0.547198
Texas   0.389365  1.497145  1.088646
Oregon  0.385908  1.832977  0.115558

In [360]:
f = lambda x: x.max() - x.min()
frame.apply(f)

b    1.909307
d    1.256327
e    0.973088
dtype: float64

In [361]:
frame.apply(f, axis='columns')

Utah      0.943292
Ohio      1.263848
Texas     1.886510
Oregon    2.218885
dtype: float64

In [362]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min','max'])

frame.apply(f)

b         d         e
min -1.519942 -1.832977 -1.088646
max  0.389365 -0.576650 -0.115558

In [363]:
format = lambda x: '%.2f' % x
frame.applymap(format)

b      d      e
Utah    -1.52  -0.58  -0.81
Ohio     0.33  -0.94  -0.55
Texas    0.39  -1.50  -1.09
Oregon   0.39  -1.83  -0.12

In [364]:
frame['e'].map(format)

Utah      -0.81
Ohio      -0.55
Texas     -1.09
Oregon    -0.12
Name: e, dtype: object

In [365]:
# sort_index 메소드
obj = pd.Series(range(4), index=['b','a','b','c'])
obj.sort_index()

a    1
b    0
b    2
c    3
dtype: int64

In [1]:
import pandas as pd
import numpy as np
frame = pd.DataFrame(np.arange(8).reshape((2,4)),
                    index=['three','one'],
                    columns = ['d','a','b','c'])
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [2]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [3]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [4]:
frame.sort_index(axis=1, ascending=False) #내림차순

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [5]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])
obj

0    4.0
1    NaN
2    7.0
3    NaN
4   -3.0
5    2.0
dtype: float64

In [6]:
obj.sort_index()

0    4.0
1    NaN
2    7.0
3    NaN
4   -3.0
5    2.0
dtype: float64

In [7]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [8]:
frame.sort_values(by='a')

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [9]:
obj = pd.Series([7,-5, 7, 4,2,0,4])
obj

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64

In [10]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

rank의 method는 동점일 경우 처리하는 방식이다. 

평균(method='average') : 동점 관측치 간의 그룹 내 평균 순위 부여 (default 설정) 
최소값(method='min') : 동점 관측치 그룹 내 최소 순위 부여 
최대값(method='max') : 동점 관측치 그룹 내 최대 순위 부여 
첫번째 값 (method='first') : 동점 관측치 중에서 데이터 상에서 먼저 나타나는 관측치 부터 순위 부여  
조밀하게 (method='dense') : 최소값('min')과 같은 방법으로 순위부여하나, 'min'과는 다르게 그룹 간 순위가 '1'씩 증가함 (like ‘min’, but rank always increases by 1 between groups)  


In [11]:

obj.rank(method='first') # 똑같은 값일 경우 먼저온게 더 높은 순위.

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [12]:
obj.rank(ascending=False) # 내림차순. 높은게 1등.

0    1.5
1    7.0
2    1.5
3    3.5
4    5.0
5    6.0
6    3.5
dtype: float64

In [13]:
obj.rank(ascending=False, method='max') 
# 동점중에서 가장 낮은 순위로 줍니다.

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [14]:
frame = pd.DataFrame({'b': [4.3,7,-3,2], 'a':[0,1,0,1],
                     'c': [-2,5,8,-2.5]})
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [15]:
frame.rank(axis = 'columns') # default method 평균인듯

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

In [16]:
obj = pd.Series(range(5), index=['a','a','b','b','c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [17]:
obj.index.is_unique

False

In [18]:
obj['a']

a    0
a    1
dtype: int64

In [19]:
df = pd.DataFrame(np.random.randn(4,3), index=['a','a','b','b'])
df

0         1         2
a  0.308142 -1.284418  1.344379
a  0.977564  0.814342  0.319759
b -0.353220 -1.107161  1.784476
b  1.413856  0.601215 -0.407593

In [20]:
df.loc['a']

0         1         2
a  0.308142 -1.284418  1.344379
a  0.977564  0.814342  0.319759

In [21]:
df.iloc[:, 1:3]

1         2
a -1.284418  1.344379
a  0.814342  0.319759
b -1.107161  1.784476
b  0.601215 -0.407593

In [22]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
                  [np.nan, np.nan], [0.75,-1.3]],
                 index=['a','b','c','d'],
                 columns=['one','two'])

df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [23]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [24]:
df.sum(axis=1)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [25]:
df.sum(axis='columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [26]:
df.mean(axis='columns')

a    1.400
b    1.300
c      NaN
d   -0.275
dtype: float64

In [27]:
# 'skipna' 는 NaN을 제외할지 결정하는것.
df.mean(axis='columns', skipna=False)
# 제외안함. 하나만 NaN이어도 계산이 되니 바로 ~~ NaN이 되버리기

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [28]:
df. idxmax()

one    b
two    d
dtype: object

In [30]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [31]:
df.cumsum()
# b = a+b
# c = a+b+c
# d = a+b+c+d

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [32]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [33]:
conda install pandas-datareader

Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\LG\anaconda3

  added / updated specs:
    - pandas-datareader


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2024.3.11  |       haa95532_0         128 KB
    certifi-2024.2.2           |  py310haa95532_0         160 KB
    openssl-1.1.1w             |       h2bbff1b_0         5.5 MB
    pandas-datareader-0.10.0   |     pyhd3eb1b0_0          71 KB
    ------------------------------------------------------------
                                           Total:         5.8 MB

The following NEW packages will be INSTALLED:

  pandas-datareader  pkgs/main/noarch::pandas-datareader-0.10.0-pyhd3eb1b0_0 

The following packages will be UPDATED:

  ca-certificates                     2023.01.10-haa95532_0 --> 2024.3.11-haa95532_0 
  certifi                         2022.12.7-py310haa9



==> WARNING: A newer version of conda exists. <==
  current version: 23.3.1
  latest version: 24.3.0

Please update conda by running

    $ conda update -n base -c defaults conda

Or to minimize the number of packages updated during conda update use

     conda install conda=24.3.0




In [35]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [37]:
uniques = obj.unique()
uniques
# 중복된 인덱스 제외하고. 인덱스 출력.

array(['c', 'a', 'd', 'b'], dtype=object)

In [40]:
obj.value_counts() #각 인덱스당 value 개수를 내림차순으로 출력.

c    3
a    3
b    2
d    1
dtype: int64

In [43]:
obj.value_counts(sort=False) # 정렬 x

c    3
a    3
d    1
b    2
dtype: int64

In [45]:
obj.isin(['b','c']) 
# obj의 index중 b와 c가 포함되어있는지를 불리언으로 나타낸다.

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [46]:
mask = obj.isin(['b','c']) 
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [48]:
unique_vals = obj.unique()
pd.Index(unique_vals).get_indexer(obj)
# 인덱스를 앞에서 부터 숫자 지정해서 출력하는거네
# c=0 a=1 b=2 d=3 인듯?

array([0, 1, 2, 1, 1, 3, 3, 0, 0], dtype=int64)